[build]
  command = "hugo"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.106.0"

[[headers]]
  for = "/*"
  [headers.values]
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' https://cdn.jsdelivr.net https://fonts.bunny.net; frame-ancestors 'self'; form-action 'self'; script-src 'self' https://hudocs.com https://*.hudocs.com https://cdn.jsdelivr.net 'sha256-mHDS1bwUA7C11WI2Lg/0s4F/QJC5+BawSdYhX8Icul0=';"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "sameorigin"
    X-XSS-Protection = "1; mode=block"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    Permissions-Policy = "geolocation=(self), microphone=(), camera=()"
    Cache-Control = "public, max-age=31536000"
    Access-Control-Allow-Origin = "*"
